### ISSUE TITLE
voms-proxy with multiple attributes does not work entirely

### ISSUE THREAD

**Issue by RHofsaess** [italiangrid/voms#111]
Hi all,
I have a question/issue concerning a voms-proxy with multiple attributes.
When initiating a voms-proxy with 
`$voms-proxy-init --rfc -bits 4096 --voms cms -valid 192:00`
I get the following proxy with my two roles in the attribute:
```
user@lx:~$ voms-proxy-info --all
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=PLACEHOLDER /CN=PLACEHOLDER /CN=PLACEHOLDER/CN=PLACEHOLDER
issuer    : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=PLACEHOLDER /CN=PLACEHOLDER /CN=PLACEHOLDER
identity  : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=PLACEHOLDER /CN=PLACEHOLDER /CN=PLACEHOLDER
type      : RFC compliant proxy
strength  : 4096 bits
path      : /tmp/x509up_PLACEHOLDER
timeleft  : 191:59:54
key usage : Digital Signature, Key Encipherment
=== VO cms extension information ===
VO        : cms
subject   : /DC=ch/DC=cern/OU=Organic Units/OU=Users/CN=PLACEHOLDER/CN=PLACEHOLDER/CN=PLACEHOLDER
issuer    : /DC=ch/DC=cern/OU=computers/CN=cms-auth.web.cern.ch
attribute : /cms/Role=NULL/Capability=NULL
attribute : /cms/dcms/Role=NULL/Capability=NULL
timeleft  : 191:59:53
uri       : voms-cms-auth.app.cern.ch:15000
```
The problem, however, is that I cannot write on our dcache storage that requires the dcms role.
As it seems, when authenticating, only the first attribute is checked and not both.
Setting the proxy up with:
`$voms-proxy-init -rfc -bits 4096 --voms cms:/cms/dcms --valid 192:00`
then works, as the dcms role is available in the first attribute.
The problem with this is that some servers in the WLCG do not recognize the dcms role, which prevents me from reading file from some T2 centers in the US for example.
Hence, I can not read or can not write...

I am not sure, if this is just a server configuration issue, but thought to ask the experts :)

Thanks

**Comment by msalle** [comment]
Hi, first of all, just to prevent confusion: you mean the dcms _group_
In VOMS you always get all the groups you're entitled to, however, the default group, i.e. the name of the VO, so `/cms` in this case, is normally the first one (i.e. the primary FQAN), unless you explicitly ask for others.
Whether your dCache storage takes secondary FQANs into account for its permissions is definitely a question for the dCache developers or your local sysadmins. Also, whether unrecognised groups are ignored or lead to a failed mapping is probably a question you need to ask them, since that will be dCache specific and most probably is configurable.

**Comment by RHofsaess** [comment]
Hi,
yes, I mean the group, sorry.
Okay, thanks for the clarification. Then I will ask our dcache team directly.
