### ISSUE TITLE
tarball created by make dist is missing several files

### ISSUE THREAD

**Issue by msalle** [italiangrid/voms#130]
On the develop branch, creating a tarball using the `make dist` target is missing several files, including for example ssl_compat.h
Run:
```
./autogen.sh
mkdir build
cd build
../configure --without-server
make dist
tar -zxvf voms-2.1.1.tar.gz
diff -qr voms-2.1.1 ..
```
will show for example several missing header files and also some documentation files (incl. manpages).

**Comment by giacomini** [comment]
PR welcome :-) but I'll have a look myself soon.

**Comment by giacomini** [comment]
@msalle please check

**Comment by msalle** [comment]
Hi, thanks!
I still see some missing files:
- some .h and .c files (for example `myproxycertinfo.[ch]`), but hard to say which ones are needed.
- I do think you need `VOMSAC.wsdl` (necessary for the server part currently) though: make distcheck fails on it.
- some manpages, in particular `voms.8` and `voms-install-replica`

**Comment by giacomini** [comment]
>     * some .h and .c files (for example `myproxycertinfo.[ch]`), but hard to say which ones are needed.

`myproxycertinfo.[ch]` are not needed any more and I've removed them. Any other?

>     * I do think you need `VOMSAC.wsdl` (necessary for the server part currently) though: make distcheck fails on it.

I see it in the tarball. `make distcheck` for me (ubuntu 22.04) fails because there are three remaining files after uninstall. 

>     * some manpages, in particular `voms.8` and `voms-install-replica`

I see voms.8 in the tarball. About `voms-install-replica` I'm trying to understand if it's still relevant or not; I see other two scripts, which are installed: `voms_replica_{master,slave}_setup.sh`
